Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[ 1,  6],
              [ 2,  8],
              [ 3, 11],
              [ 3, 10],
              [ 1,  7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis=0)

In [6]:
mean_a

array([2. , 8.4])

In [14]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])