Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[ 1,  6],
              [ 2,  8],
              [ 3, 11],
              [ 3, 10],
              [ 1,  7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis=0)

In [6]:
mean_a

array([2. , 8.4])

In [14]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [16]:
a_centered_sp = a_centered.dot(a_centered.T)
a_centered_sp

array([[ 6.76,  0.96, -7.24, -4.84,  4.36],
       [ 0.96,  0.16, -1.04, -0.64,  0.56],
       [-7.24, -1.04,  7.76,  5.16, -4.64],
       [-4.84, -0.64,  5.16,  3.56, -3.24],
       [ 4.36,  0.56, -4.64, -3.24,  2.96]])

In [17]:
print (a_centered_sp / (a_centered_sp.ndim - 1))

[[ 6.76  0.96 -7.24 -4.84  4.36]
 [ 0.96  0.16 -1.04 -0.64  0.56]
 [-7.24 -1.04  7.76  5.16 -4.64]
 [-4.84 -0.64  5.16  3.56 -3.24]
 [ 4.36  0.56 -4.64 -3.24  2.96]]
